### ISSUE TITLE
4 - Scheda Tecnica - Print Buttons

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#10]
Add following print buttons:
a.	Print PDF SCHEDA TECNICA
b.	Print EXCEL SCHEDA TECNICA

**Comment by mattianobile** [comment]
Bottone aggiunto

![image](https://user-images.githubusercontent.com/75784417/132220054-4add7263-6201-407f-9fb1-af3d5e4a9bd1.png)
