### ISSUE TITLE
7 - Scheda Tecnica - Import Functionality

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#14]
Define an Import button on SCHEDA TECNICA.
The import button will require the SCHEDA TECNICA number and the raw material FOGLIO.
If fill only the scheda tecnica number then it will be copied all SCHEDA TECNICA, if fill scheda tecnica number + raw material FOGLIO then il will be copied only the specific FOGLIO including all objects excluded the finish product.

**Comment by mattianobile** [comment]
Predisposto bottone e popup per importazione

![image](https://user-images.githubusercontent.com/75784417/132356905-6dd24e79-0379-4b8f-84c2-184a2a08c58b.png)

**Comment by mattianobile** [comment]
Fatto
