### ISSUE TITLE
8 - Scheda Tecnica - New Raw Material

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#15]
Add a new box with different colour for raw material different by FOGLIO. 
The UDM can be KG and PEZZI but not FOGLIO.
Remove Coprienza field by raw material FOGLIO.

**Comment by mattianobile** [comment]
Fatto

![image](https://user-images.githubusercontent.com/75784417/132373042-e9d88e26-b9b7-41ed-9847-a89c67f8358f.png)
