### ISSUE TITLE
9 - Scheda Tecnica - Pallet type check

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#16]
In Finish good box if Pallet Type (Tipo Imballaggio) is "Specifico" then the related raw material must be required.
Add this control during save activity.

**Comment by mattianobile** [comment]
Nel caso in cui il Finish Good ha Tipo Pallet = Specifico allora deve esistere un Raw Material del nuovo tipo (non giallo)

**Comment by mattianobile** [comment]
Fatto
