### ISSUE TITLE
11 - Scheda Tecnica - add Customer attributes

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#18]
For finish good, in secondary tab add following attributes:

a.	Gruppo (read only mode)
b.	Cliente finale (read only mode)

Rename "Cliente di riferimento
![Screenshot_108](https://user-images.githubusercontent.com/89785345/132220406-323ae320-5a5c-4728-910a-91ed064a395f.png)
" in "Marca" and set in read only mode.

**Comment by mattianobile** [comment]
Rinominato campo "Cliente di riferimento" in "Cliente Finale" e aggiunto campo "Gruppo". Entrambi read only
