### ISSUE TITLE
12 - Scheda Tecnica - Create Search Page

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#19]
Create a new page to search scheda tecnica just created in the past.

The criteria must be the following:
End Customer
Group
Marca
Scheda Tecnica number
Codice di Progettazione
ID Prodotto Finito
Codice commessa

Also the result table must show the same columns above.

The scheda tecnica must be open with an hyperlink by result page.

For Quotation the criteria must be:
Quotation number
Scheda Tecnica number
End Customer
Group
Marca

The quotation must be open with an hyperlink by result page.

**Comment by imandatelli** [comment]
- 2 pagine diverse per sk e quot
- quando cerco mi popola una tabellina: seleziono un record e mi rimanda alla pagina prepopolata
