### ISSUE TITLE
1- Scheda Tecnica: Unità di Misura di consumo

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#2]
Per il box raw material, sul tab calculation è riportato il campo "Unità di Misura di Consumo".
Aggiungere i valori  Fogli e Pezzi.

![Screenshot_103](https://user-images.githubusercontent.com/89785345/131707249-5c813d43-0f1a-436f-954f-b4d7f8b5215e.png)

**Comment by mattianobile** [comment]
Aggiunti
