### ISSUE TITLE
Inserire BU

### ISSUE THREAD

**Issue by imandatelli** [imandatelli/Pusterla_Scheda_Tecnica#20]
![image](https://user-images.githubusercontent.com/89082462/132674106-00f9ae59-3c83-4d8f-8224-c1fd4d032dd5.png)

Inserire la BU / Bandierina dell'utente

**Comment by mattianobile** [comment]
Bandierina aggiunta (per ora solo Francia)

![image](https://user-images.githubusercontent.com/75784417/132694306-470309f8-ad46-46c1-959f-d0281fecef1c.png)
