### ISSUE TITLE
1 - Preventivo: Gestione campo quantità

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#5]
Rimuovere il pulsante Aggiorna.

Predisporre un pulsante alla destra del campo quantità chiamato "Calcola Preventivo".

Il pulsante dovrà svolgere tutti i calcoli del preventivo (NON per il Mock-Up).

Per il Mock-Up dovrà compilare una tabella da predisporre sempre sul medesimo tab "Riepilogo" da posizionare sotto i campi pre-esistenti:

![Screenshot_106](https://user-images.githubusercontent.com/89785345/131709631-3736f40a-dc49-4342-a856-174667fd72da.png)

La tabella dovrà essere in sola lettura ed avere le seguenti colonne:
- Quantità con il valore digitato sul campo di inserimento
- Prezzo (sarà calcolato, per ora inseriamo un valore fisso ma diverso per quantità, prevediamo solo tre quantità 500, 1000, 2000)
- Pulsante "Invia verso ERP". Se viene premuto in corrispondenza di una riga, sulle altre si disabilita.

**Comment by imandatelli** [comment]
MainID -> Vers. Preventivo
Togliere il pulsante Pubblica
