### ISSUE TITLE
2 - Scheda Tecnica - Notes Field - Extended Area

### ISSUE THREAD

**Issue by raspaf** [imandatelli/Pusterla_Scheda_Tecnica#8]
For each Note clicking on related field open a pop-up with an extended text area

**Comment by mattianobile** [comment]
I campi di testo (input text e text area) non sembrano gestire l'evento click.
Per ora aggiunto un bottone all'interno del campo di testo che al click apre un popup con il testo delle note

![image](https://user-images.githubusercontent.com/75784417/132327667-e14df8d2-af1a-43fb-aaa0-a0abced1338b.png)
